### ISSUE TITLE
Add support for ng-disabled

### ISSUE THREAD

**Issue by joshfriend** [xpepermint/angular-ui-switch#9]

**Comment by JobaDiniz** [comment]
+1
@joshfriend have you figure it out some way?

**Comment by JobaDiniz** [comment]
Looking at code switch [code](https://github.com/xpepermint/angular-ui-switch/blob/master/angular-ui-switch.js), I think in order to support ng-disabled, a bit of refactoring is needed. The code is so simple, it just manage html...

In summary, in order to support disabled, directive should require _ngModel_ and only change model value if it is not disabled.

**Comment by joshfriend** [comment]
I did not come up with a way to use `ng-disabled` (i didn't try yet actually). I just `ng-hide` the whole element for now.

**Comment by xpepermint** [comment]
https://github.com/xpepermint/angular-ui-switch/pull/23
